### ISSUE TITLE
"Variables Again" Doesn't Seem to Compile

### ISSUE THREAD

**Issue by mikegajda** [johnSerrano/Cwalk#1]
Attempting to compile the code in "Variables Again" generates this error:

```
main.c:14:9: warning: implicit declaration of function 'f' is invalid in C99
      [-Wimplicit-function-declaration]
        f(n);
        ^
main.c:19:6: error: conflicting types for 'f'
void f(int n)
     ^
main.c:14:9: note: previous implicit declaration is here
        f(n);
```

The following should be added to make it compile just after the #include statement, I believe:

`void f(int n);`

**Comment by johnSerrano** [comment]
Thank you, variables_again has been updated to resolve this.
